drop table if exists bookings;
drop table if exists requests;
drop table if exists comments;
drop table if exists items;
drop table if exists users;
create table if not exists users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255),
    email varchar(512),
    constraint pk_user primary key (id),
    constraint UQ_USER_EMAIL unique (email)
);
create table if not exists items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255),
    description varchar(512),
    available boolean,
    owner_id bigint references users,
    request_id bigint,
    constraint pk_item primary key (id)
);
create table if not exists bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    status varchar(512),
    item_id bigint references items,
    booker_id bigint references users,
    constraint pk_booking primary key (id)
);
create table if not exists requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(512),
    requestor_id bigint not null references users,
    created timestamp,
    constraint pk_request primary key (id)
);
create table if not exists comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(512),
    created timestamp,
    item_id bigint not null references items,
    author_id bigint not null references users,
    constraint pk_comments primary key (id)
);